src/Entity/Services.php
<?php

/*
 * Copyright (c) OktoDark Studios
 * Website: https://www.oktodark.com
 *
 * Author: Razvan George H. (Viruzzz)
 *
 * For the full copyright and license information, please view the LICENSE.
 */

namespace App\Entity;

use App\Repository\ServicesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ServicesRepository::class)]
#[ORM\Table(name: 'services')]
class Services
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING)]
    #[Assert\Length(max: 100)]
    private ?string $serviceName = null;

    #[ORM\Column(type: Types::STRING)]
    #[Assert\Length(max: 20)]
    private ?string $servicePrice = null;

    #[ORM\Column(type: Types::STRING)]
    #[Assert\Length(max: 10)]
    private ?string $serviceWorkDays = null;

    #[ORM\Column(type: Types::STRING)]
    #[Assert\Length(max: 10000)]
    private ?string $ServiceToDo = null;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id): void
    {
        $this->id = $id;
    }

    public function getServiceName(): ?string
    {
        return $this->serviceName;
    }

    public function setServiceName(?string $serviceName): void
    {
        $this->serviceName = $serviceName;
    }

    public function getServicePrice(): ?string
    {
        return $this->servicePrice;
    }

    public function setServicePrice(?string $servicePrice): void
    {
        $this->servicePrice = $servicePrice;
    }

    public function getServiceWorkDays(): ?string
    {
        return $this->serviceWorkDays;
    }

    public function setServiceWorkDays(?string $serviceWorkDays): void
    {
        $this->serviceWorkDays = $serviceWorkDays;
    }

    public function getServiceToDo(): ?string
    {
        return $this->ServiceToDo;
    }

    public function setServiceToDo(?string $ServiceToDo): void
    {
        $this->ServiceToDo = $ServiceToDo;
    }
}

src/Controller/InfoController.php
<?php

/*
 * Copyright (c) OktoDark Studios
 * Website: https://www.oktodark.com
 *
 * Author: Razvan George H. (Viruzzz)
 *
 * For the full copyright and license information, please view the LICENSE.
 */

namespace App\Controller;

use App\Form\ContactType;
use App\Repository\ServicesRepository;
use App\Repository\SettingsRepository;
use App\Repository\TeamRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Attribute\Route;

final class InfoController extends AbstractController
{
    #[Route('/about', methods: ['GET'], name: 'about')]
    public function about(SettingsRepository $settings, TeamRepository $team): Response
    {
        return $this->render('@theme/info/about.html.twig', [
            'settings' => $settings->findAll(),
            'team' => $team->findAll(),
        ]);
    }

    #[Route('/contact', methods: ['GET'], name: 'contact')]
    public function contact(SettingsRepository $settings, Request $request, MailerInterface $mailer): Response
    {
        $form = $this->createForm(ContactType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactFormData = $form->getData();

            $email = (new Email($contactFormData['subject']))
                ->from($contactFormData['email'])
                ->to('contact@oktodark.com')
                ->html($contactFormData['message'])
            ;

            $mailer->send($email);

            $this->addFlash('success', 'Message Send!');

            return $this->redirectToRoute('contact');
        }

        return $this->render('@theme/info/contact.html.twig', [
            'settings' => $settings->findAll(),
            'form' => $form,
        ]);
    }

    #[Route('/faq', methods: ['GET'], name: 'faq')]
    public function faq(SettingsRepository $settings): Response
    {
        $selectSettings = $settings->findAll();

        return $this->render('@theme/info/faq.html.twig', ['settings' => $selectSettings]);
    }

    #[Route('/privacy-policy', methods: ['GET'], name: 'privacy-policy')]
    public function privacypolicy(SettingsRepository $settings): Response
    {
        return $this->render('@theme/info/privacy-policy.html.twig', [
            'settings' => $settings->findAll(),
        ]);
    }

    /**
     * @Route("/services", methods="GET", name="services")
     */
    #[Route('/services', methods: ['GET'], name: 'services')]
    public function services(SettingsRepository $settings, ServicesRepository $services): Response
    {
        return $this->render('@theme/info/services.html.twig', [
            'settings' => $settings->findAll(),
            'services' => $services->findAll(),
        ]);
    }
}

templates/grey/info/about.html.twig
{% extends "@theme/base.html.twig" %}

{% block title %}{{ 'title.about'|trans }}{% endblock %}

{% block head %}
    {{ parent() }}
{% endblock %}

{% block body_id 'about' %}

{% block main %}

    <section class="section section-page-title context-dark">
        <div class="container">
            <h2>{{ 'title.about'|trans }}</h2>
        </div>
    </section>

    <section class="section section-lg bg-gray-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <p>{{ 'about.description'|trans|raw }}</p>
                </div>
            </div>
        </div>
    </section>
    <section class="section section-lg bg-default text-center">
        <div class="container">
            <h3>{{ 'title.our_team'|trans }}</h3>
            <div class="row">

                {% for t in team %}
                    <div class="col-12">
                        <div class="box-team-modern box-team-modern-quote">
                            <figure class="team-img">
                                <img class="rounded-circle" src="{% for s in settings %}{{ s.siteCDN }}{% endfor %}/themes/grey/images/not_available.png" alt="" width="210" height="210"/>
                            </figure>
                            <div class="box-team-modern-caption">
                                <h5 class="team-modern-subtitle">{{ t.position }}</h5>
                                <h4 class="team-modern-title">{{ t.name }}</h4>
                                <p>{{ t.description }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>

{% endblock %}

templates/grey/info/contact.html.twig
{% extends "@theme/base.html.twig" %}

{% block title %}{{ 'title.contact'|trans }}{% endblock %}

{% block head %}
    {{ parent() }}
{% endblock %}

{% block body_id 'contact' %}

{% block main %}

    <section class="section section-page-title context-dark">
        <div class="container">
            <h2>{{ 'title.contact'|trans }}</h2>
        </div>
    </section>

    <section class="section section-lg bg-default text-center">
        <div class="container">
            <div class="row justify-content-lg-center">
                <div class="col-md-9 col-lg-7">
                    <p>{{ 'content.contact'|trans }}</p>
                    <br>
                    <div>
                    {{ form_start(form, {'attr' : { 'class' : 'rd-mailform text-left', 'data-form-output': 'form-output-global', 'data-form-type': 'contact' } }) }}
                        <div class="form-warp">
                            {{ form_widget(form) }}
                        </div>
                    {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/grey/info/faq.html.twig
{% extends "@theme/base.html.twig" %}

{% block title %}{{ 'title.faq'|trans }}{% endblock %}

{% block head %}
    {{ parent() }}
{% endblock %}

{% block body_id 'faq' %}

{% block main %}

    <section class="section section-page-title context-dark">
        <div class="container">
            <h2>{{ 'title.faq'|trans }}</h2>
        </div>
    </section>

    <section class="section section-lg bg-default">
        <div class="container">
            <div class="text-decoration">
                <dl class="list-terms">
                    <dt class="heading-4">{{ 'faq.one_title_txt'|trans }}</dt>
                    <dd>{{ 'faq.one_content_txt'|trans|raw }}</dd>
                    <dt class="heading-4">{{ 'faq.two_title_txt'|trans }}</dt>
                    <dd>{{ 'faq.two_content_txt'|trans }}</dd>
                    <dt class="heading-4">{{ 'faq.three_title_txt'|trans }}</dt>
                    <dd>{{ 'faq.three_content_txt'|trans|raw }}</dd>
                </dl>
            </div>
        </div>
    </section>

{% endblock %}

templates/grey/info/privacy-policy.html.twig
{% extends "@theme/base.html.twig" %}

{% block title %}{{ 'title.privacy'|trans }}{% endblock %}

{% block head %}
    {{ parent() }}
{% endblock %}

{% block body_id 'privacy-policy' %}

{% block main %}

    <section class="section section-page-title context-dark">
        <div class="container">
            <h2>{{ 'title.privacy'|trans }}</h2>
        </div>
    </section>

    <section class="section section-lg bg-default">
        <div class="container">
            <div class="text-decoration">
                <dl class="list-terms">
                    {{ 'privacy.section'|trans|raw }}
                </dl><a class="privacy-link" href="mailto:contact@oktodark.com">contact@oktodark.com</a>
            </div>
        </div>
    </section>

{% endblock %}

templates/grey/info/services.html.twig
{% extends "@theme/base.html.twig" %}

{% block title %}{{ 'title.services'|trans }}{% endblock %}

{% block head %}
    {{ parent() }}
{% endblock %}

{% block body_id 'services' %}

{% block main %}

    <section class="section section-page-title context-dark">
        <div class="container">
            <h2>{{ 'title.services'|trans }}</h2>
        </div>
    </section>

    <section class="section section-lg bg-gray-100">
        <div class="container">
            <div class="row row-cols-1 row-cols-md-4 mb-4 text-center">
                {% for e in services %}
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-3">
                                <h4 class="my-0 fw-normal">{{ e.serviceName }}</h4>
                            </div>
                            <div class="card-body">
                                {{ 'services.from'|trans }}
                                <h3 class="card-title pricing-card-title"><i class="fas fa-euro-sign fa-xs"></i>{{ e.servicePrice }}<small class="text-muted">&numsp;/&numsp;{{ e.serviceWorkDays }}</small></h3>
                                <ul class="list-unstyled mt-3 mb-4">
                                    {{ e.serviceToDo|raw }}
                                </ul>
                                <a href="{{ path('contact') }}" class="btn btn-lg btn-block btn-primary but-contact-us"><h6 style="color: white">{{ 'services.contact_us'|trans }}</h6></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="service-notes">{{ 'services.notes'|trans }}</div>
            </div>
        </div>
    </section>

{% endblock %}